### ISSUE TITLE
1033 statement

### ISSUE THREAD

**Issue by sleepntsheep** [programming-in-th/statements#6]
![pic](https://cdn.discordapp.com/attachments/953642337995735101/962373379288104990/unknown.png)

this line is wrong, it should be

4(i-1) + m + i เป็นข้อมูลการเดินครั้งที่ m ของผู่้เล่นคนที่ i

as the example shown here 

![ex](https://cdn.discordapp.com/attachments/953642337995735101/962373668112068618/unknown.png)

**Comment by Thunyatorn** [comment]
#11 done
